logging:
  level:
    org:
      springfrimework:
        data: DEBUG
# 数据源的配置 #
spring:
  datasource:
    jpa:
      show-sql: true
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: root
    password: zhaoCC33
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: zhaoCC33
    #连接超时时间
    timeout: 5000